use_frameworks!

platform :ios, '9.0'

target 'AddCocoapodProject_Example' do
  pod 'AddCocoapodProject', :path => '../'

  target 'AddCocoapodProject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
